# Generated by Django 3.0 on 2026-06-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='USER',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='bloodgroup',
            field=models.CharField(max_length=10),
        ),
    ]
