# Generated by Django 3.0 on 2026-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20260602_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bloodgroup',
            field=models.CharField(default='', max_length=20),
        ),
    ]
