# Generated by Django 3.0 on 2026-06-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_users_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='DONOR',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_requests', to='bloodapp.Users'),
        ),
    ]
