# Generated by Django 3.0 on 2026-06-05 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodapp', '0004_bloodrequest_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
