# Generated by Django 3.0 on 2026-06-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_bloodrequest_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='USER',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='DONOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_requests', to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_requests', to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
