# Generated by Django 3.0 on 2026-06-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_auto_20260605_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='DONOR',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='donor_for', to='bloodapp.Users'),
        ),
    ]
