# Generated by Django 3.0 on 2026-06-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0007_auto_20260605_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='DONOR',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.Users'),
        ),
    ]
