# Generated by Django 3.0 on 2026-06-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0008_auto_20260605_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='DONOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_requests', to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
