# Generated by Django 3.0 on 2026-06-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0009_auto_20260605_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='bloodapp.Users'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
