# Generated by Django 3.0 on 2026-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0010_auto_20260605_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hemoglobin',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='lastdonation',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
